# Generated by Django 4.2.2 on 2023-07-26 23:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('short_link', models.CharField(blank=True, max_length=15, unique=True)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exp_date', models.SmallIntegerField(default=90)),
                ('user_host', models.CharField(blank=True, max_length=40, null=True)),
                ('user_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('short_url', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shortlink.shorturl')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
