# Generated by Django 4.2.2 on 2023-07-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='user_host',
            new_name='user_ip',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='user_name',
        ),
    ]
